import type { Metadata } from "next";
import { Roboto, Quicksand } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto"
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} ${roboto.className}`}>{children}</body>
    </html>
  );
}
